### ISSUE TITLE
Make libary ansible galaxy compatible

### ISSUE THREAD

**Issue by ofriedri** [univention/ansible-modules#1]
This library should be made compatible to Ansible galaxy, so that it can be easily installed, like:

`ansible-galaxy install -c --roles-path roles --role-file requirements-external.yml`

With the following requirements-external.yml:
```
---

roles:
  - name: ucr-facts
    scm: git
    version: v0.1.1
    src: https://github.com/univention/ansible-modules.git
```
To make this work, this repo has to adhere to the ansible galaxy structure by providing some meta information, see https://github.com/ofriedri/univention-ansible-ucr for reference.
