### ISSUE TITLE
univention_directory_manager module: `--policy-reference` and `--policy-dereference` options not available

### ISSUE THREAD

**Issue by Daenou** [univention/ansible-modules#18]
Today I tried to create and reference a policy with the univention.ucs_modules.univention_directory_manager ansible module, only to find out that the option `--policy-reference` and `--policy-dereference` options are not implemented in this module at all.

As a workaround, instead of using an ansible shell command I created an extended attribute, so I can reference and dereference policies of groups in this example:
```
# Workaround
# univention.ucs_modules.univention_directory_manager doesn't support the "--policy-reference" and "--policy-dereference" commands yet.
# So I create an extended attibute to still be able to set policy references for groups via UDM.
# See issue: <url>
- name: Get LDAP base
  ansible.builtin.command: ucr get ldap/base
  check_mode: false
  changed_when: false
  register: "register_ea_ldap_base"
  when:
    - "ucschool_register_serverrole.stdout == 'domaincontroller_master'"

- name: Create univentionLastUsedValue extended attribute
  univention.ucs_modules.univention_directory_manager:
    module: settings/extended_attribute
    position: "cn=custom attributes,cn=univention,{{ register_ea_ldap_base.stdout }}"
    dn: "cn=univentionPolicyReference,cn=custom attributes,cn=univention,{{ register_ea_ldap_base.stdout }}"
    set_properties:
      - property: "name"
        value: "univentionPolicyReference"
      - property: "CLIName"
        value: "univentionPolicyReference"
      - property: "ldapMapping"
        value: "univentionPolicyReference"
      - property: "module"
        value: "groups/group"
      - property: "objectClass"
        value: "univentionPolicyReference"
      - property: "shortDescription"
        value: "univentionPolicyReference:"
      - property: "syntax"
        value: "string"
      - property: "multivalue"
        value: "1"
      - property: "mayChange"
        value: "1"
  when:
    - "ucschool_register_serverrole.stdout == 'domaincontroller_master'"
```

Works fine with this code:
```
- name: Reference adm-accounts-read-only policy on ADM Accounts Read Only group
  univention.ucs_modules.univention_directory_manager:
    module: "groups/group"
    dn: "cn=ADM Accounts Read Only,cn=groups,dc=ldap,dc=base"
    set_properties:
      - property: univentionPolicyReference
        value: "cn=adm-accounts-read-only,cn=UMC,cn=policies,dc=ldap,dc=base"
  when:
    - "ucschool_register_serverrole.stdout == 'domaincontroller_master'"
```

Of course, you'd need additional extended attributes to reference policies to `users/user` and `containers/ou` objects.

Would be nice if this feature would be implemented

**Comment by tbreiden** [comment]
in your example you can add a list of to set policies as:
```yaml
  tasks:
    - name: "create user"
      univention_directory_manager:
        module: 'users/user'
        state: 'present'
        position: 'dc=ucs,dc=test'
        policies:
          - 'cn=udm-license,cn=operations,cn=UMC,cn=univention,dc=ucs,dc=test'
          - 'XY'
        set_properties:
          - property: 'username'
            value: 'testuser1'
          - property: 'lastname'
            value: 'testuser1'
```

**Comment by vakilics** [comment]
Hi, 
I tested with following and all works fine: 
```
---
- name: create a user
  hosts: pdn
  gather_facts: no
  tasks:
  - name: modify testuser - assign policy
    univention_directory_manager:
      module: 'users/user'
      state: 'present'
      filter: '(uid=testuser)'
      policies:
        - "cn=default-udm-self,cn=UMC,cn=policies,dc=lhh,dc=de"
        - "cn=default-settings,cn=routing,cn=dhcp,cn=policies,dc=lhh,dc=de"
        - "cn=default-umc-all,cn=UMC,cn=policies,dc=sh,dc=dev"

```
and run the playbook: 
ansible-playbook -i inventory exmpl_plcy_assign.yml

```
/usr/lib/python3/dist-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/lib/python3/dist-packages/paramiko/transport.py:237: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 45.0.0.
  "class": algorithms.Blowfish,
/usr/lib/python3/dist-packages/paramiko/transport.py:261: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "class": algorithms.TripleDES,

PLAY [create a user] *******************************************************************************************************************

TASK [modify testuser - assign policy] *************************************************************************************************
[WARNING]: Platform linux on host 10.200.34.120 is using the discovered Python interpreter at /usr/bin/python3.11, but future
installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.17/reference_appendices/interpreter_discovery.html for more information.
ok: [10.200.34.120]

PLAY RECAP *****************************************************************************************************************************
10.200.34.120              : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
The result : 
```
root@primary:~# udm users/user list --filter  uid=testuser | grep univentionPolicyReference
  univentionPolicyReference: cn=default-udm-self,cn=UMC,cn=policies,dc=lhh,dc=de
  univentionPolicyReference: cn=default-settings,cn=routing,cn=dhcp,cn=policies,dc=lhh,dc=de
  univentionPolicyReference: cn=default-umc-all,cn=UMC,cn=policies,dc=sh,dc=dev

```
