### ISSUE TITLE
error handling if an object already exists

### ISSUE THREAD

**Issue by fbim-genosr** [univention/ansible-modules#5]
Hi all,

when adding an object that already exists, let's say a user, or an OU, 

```
- name: Organisationsstrukturen in UCS anlegen
        tags: ou
        univention.ucs_modules.univention_directory_manager:
          module: 'container/ou'
          state: 'present'
          position: 'dc=thing,dc=some,dc=domain'
          dn: 'dc=thing,dc=some,dc=domain'
          set_properties:
            - property: 'name'
              value: 'some'
.....
```
I get a trace back, telling me, 

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: univention.udm.exceptions.CreateError: Error creating 'container/ou' object: Das Objekt existiert bereits. (ou=some,dc=thing,dc=some,dc=domain)
`

IMHO, the module should just return "ok", because the object is already existing. Or am I mixing things up here?

Cheers 
Sebastian
