### ISSUE TITLE
univention_directory_module: superordinate option not available

### ISSUE THREAD

**Issue by Daenou** [univention/ansible-modules#7]
I tried creating an object that needs the UDM CLI option `--superordinate` to be created.

I've tried a bunch different ways but none worked, but I haven't found superordinate in the source code anywhere so I guess it's not implemented yet.

My code:
```yaml
---
- name: Test UDM
  hosts: testhost
  tasks:
    - name: UDM
      univention.ucs_modules.univention_directory_manager:
        module: "settings/extended_attribute"
        dn: "cn=owncloudgroup,cn=custom attributes,cn=univention,dc=school,dc=ch"
        position: "cn=custom attributes,cn=univention,dc=school,dc=ch"
        set_properties: 
          - property: CLIName
            value: OwnCloudGroup
          - property: groupName
            value: school-Cloud
          - property: groupPosition
            value: "1"
          - property: ldapMapping
            value: customAttributeOwnCloudGroup
          - property: longDescription
            value: "school-Cloud activate, use 0 or 1 (customAttributeOwnCloudGroup)"
          - property: mayChange
            value: "1"
          - property: module 
            value: groups/group
          - property: multivalue
            value: "0"
          - property: name
            value: owncloudgroup
          - property: objectClass
            value: customAttributeGroups
          - property: shortDescription
            value: customAttributeOwnCloudGroup
          - property: tabName
            value: ICT
          - property: tabPosition
            value: "1"
```

Of course, this could be workarounded with a shell command, but that's not really the idea of ansible.
